apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYnFnQm5qQUphT0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1qRXhORFU0TVRWYUZ3MHpOVEF6TVRreE5UQXpNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrYldYaTRqRllaWnl4dDBYRTdOOFBUYXBLcG9JcE5LZWZ5RW5vN3J0U1pVWUtJZURGQUJ6RW93SXYKN1NpSFR1aGIvS3hTZ3NiYStKYzk5dkpiSk90d1U3WnJOcXRWb0tpRU1JVWt6TmNOeHpnM1QzQUErWUt6RjlBVwppS25KaDlvZU4zZjFQWlVsckJNbnJZc3BkWUk0RXdXSEUwbDBYRG11Q0JISmliK0dXUkdSZ2cxMUNSUldzb0dWCldSRkM0by9JZTdBL0hLU1JmTkI2ckRPcTNKeitmRVdHb1IxNkdmN2pwL0ZOM3VGT0hCc2NJd0pOaXRnYjdYUWwKTFRubmMxNUNaUnE2NHZuWUJpTWFGRE5BWERCQ2JoZHRIMU5nQUM2Qkd4VENVT3NqMnZKRm93L0k4eUF1Q0VwYwpueTVVaTdoWHB0OU1ZclNhVU5BWk01cUxKOE1OQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUVQ0Y2lRVGNPYWI5ZTUweHdsSnJLMVNIUWVqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTdvWm5ndEdlbApwQXlMSE5weThzdllyV2hGNXFJdXZUQ0txUTh2bmFDQk84SEtBM0JsTjdlZW5FOElPLzJxb0xCamFUUW4zRm5lClhqVUZqY2xnZlkyd0VockNmTWNJTHB6VXJSZ0xjNFhiZzJHUFc1VjF3c0c4MkhYVkFIVTBwU3ZGbGVjZ1B1WGwKb29BamZaeU9RSHpiU3FESG5uUjNCZmowT1FiR1A3T3lDVGRZbmJESlJQbXNCeW9taGFCZlNzdGR0YXJ2UXJ3bwpaQ0FSNUZGTE0zWi9Ua3djdUZPeXIvTGdWYjJRL3hzN3VkOXp3K0x5c1YrNTNXdlJ1dk55bTZWcjFIWFgzNE10ClZRYi90N1piUkpkeTJzZ05BMzZReUFNZzRrYUpWeEdnTWx4Yk9ibWlIaVQvTWNpald6Mnk1NWZua1BPdjhDSVkKTXJjc0hFTml0cW44Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://C0AC23FD2871A4083D10CF7B8D277081.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
    user: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
  name: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
current-context: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:010526247405:cluster/my-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster
      - --output
      - json
      command: aws
