name: Deploy

on:
  workflow_run:
    workflows: ["Dockerize"]
    types:
      - completed
    branches:
      - main  # Ensure this workflow only runs for the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}  # Checkout the correct branch

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region ${{ secrets.AWS_REGION }} --kubeconfig kubeconfig.yaml

      - name: Verify cluster access
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

      - name: Verify deployment
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl rollout status deployment/node-app