name: Dockerize

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - main  # Ensure this workflow only runs for the main branch

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-k8s-production:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-k8s-production:${{ github.sha }} .

      - name: Push Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-k8s-production:latest

      - name: Push Docker image (commit SHA)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-k8s-production:${{ github.sha }}